INSERT INTO TBL_ARTICLE (ID, TITLE, SHORT_DESCRIPTION, LONG_DESCRIPTION, CREATED_BY, CREATED_DATE, IMAGE_URL) 
VALUES 
(1, 'Very special offers! Get cashback 20% or up to USD10.', 'Special offer: Get up to 30 extra minutes of massage at select spas.', 'Offer every Friday, Saturday, and Sunday from 14 February to 31 July 2024. Get 20% cashback or up to $20 per month. Payment from KHR40,000 or USD10 per transaction. This cashback will be credited to your account no later than the 20th of the next month. We reserve the rights to change the conditions or terminate this promotion without prior notice.', 'KAKA', '2024-07-22', 'https://khmerapsaraphone.com/wp-content/uploads/2022/08/Huawei-MatePad-Pro-12.jpg'),

(2, 'Get US$10 off', 'Special offer: Get $10 off your purchase. Get up to KHR800,000 every month.', 'Free 1 night for 1 night stay for payment with ACLEDA Visa Platinum. Cardholder shall make a reservation at info@bolbeachclub.com or +855 17 505 444. Get 25% off when you pay with all types of ACLEDA Visa cards. The offer is valid from now until July 31, 2024. Privilege is not included in major holidays in Cambodia. We reserve the right to change the terms and conditions or terminate the promotion without prior notice.', 'KAKA', '2024-07-22', 'https://soklyphone.com/storage/SAMSUNG/Phone/Galaxy-Z-Flip3-5G/green-new-16332354616KkOc.png'),

(3, 'Dell Alienware M15 R6 Core i7-11800H', 'Special offer: Get an extra 15 minutes of massage.', 'The discount offer is applicable for payments made by ACLEDA Visa Platinum. The offer is valid from now until July 31, 2024. The discount offer is limited to one use per card per day at the same shop and cannot be used in conjunction with any other promotions. The discount offer is limited to 90 offers per month. We reserve the right to change the terms and conditions or terminate the promotion without prior notice.', 'KAKA', '2024-07-22', 'https://www.mastertechkh.com/storage/images/26-Jul-2022-095903_62dfbae77ee7d.jpg'),

(4, 'MacBook Air M2 Chip - 8GB - 256GB (Midnight) MLY33', 'Special offer: Get up to 30 extra minutes of massage.', 'The offer is applicable for payments made by ACLEDA Visa Platinum. The offer is valid from now until July 31, 2024. Please make a reservation in advance via https://www.bodia-spa.com or +855 92 671 937 and present the ACLEDA Visa Platinum on arrival to get this offer. The discount offer cannot be redeemed or exchanged for cash and cannot be used in conjunction with any other promotions. We reserve the right to change the terms and conditions or terminate the promotion without prior notice.', 'KAKA', '2024-07-22', 'https://www.mastertechkh.com/storage/images/11-Feb-2023-183331_63e7df7b50bbf.jpg'),

(5, 'One night free at InterContinental Maldives Maamunagau Resort', 'Special offer: Get one night free at InterContinental Maldives.', 'Offer is valid every Fri, Sat, & Sun from 01 June to 31 July 2024 or while stocks last. Discount up to KHR40,000 or USD10 per transaction. A customer gets 1 time discount per day. We reserve the rights to change the terms or terminate this program without prior notice.', 'KAKA', '2024-07-22', 'https://www.mastertechkh.com/storage/products/7xNiS7E0viO2JkrJYB6fswvk3Ln9BJ-metaUk9HX0ZMT1dfWjEzX2JsYWNrXzA4NjQuanBn-.jpg');
